server_name: alpha
listen: 0.0.0.0:4222
http_port: 8222

jetstream {
  store_dir: /Users/daichi/nats-data/jetstream
  max_mem: 256MB
  max_file: 1GB
}

cluster {
  name: syutain
  listen: 0.0.0.0:6222
  routes: [
    nats-route://100.75.146.9:6222
    nats-route://100.70.161.106:6222
    nats-route://100.82.81.105:6222
  ]
}

log_file: "/Users/daichi/nats-data/logs/nats-server.log"
log_size_limit: 10MB
